channels:
   - conda-forge

dependencies:
   - sphinx==3.1.1
   - Jinja2==2.11
   - docutils==0.15.2
   - bokeh
   - ipython
   - pandas
   - pip
   - pip:
      - https://github.com/mchoi8739/sagemaker-debugger.git@smdebug-sphinx-apidoc-2 
